## Welcome to NUMPY Class (done through Markdown)

In [13]:
import numpy as np
import matplotlib.pyplot as plt

In [27]:
data = np.arange(20)

In [28]:
arr1 = np.arange(1,11)
arr2 = np.linspace(7000, 32000, 10, dtype = 'int32')

In [29]:
new_arr = np.column_stack((arr1, arr2))

In [30]:
new_arr

array([[    1,  7000],
       [    2,  9777],
       [    3, 12555],
       [    4, 15333],
       [    5, 18111],
       [    6, 20888],
       [    7, 23666],
       [    8, 26444],
       [    9, 29222],
       [   10, 32000]])

In [18]:
new_arr.shape

(10, 2)

In [31]:
print(new_arr.reshape(5,4))

[[    1  7000     2  9777]
 [    3 12555     4 15333]
 [    5 18111     6 20888]
 [    7 23666     8 26444]
 [    9 29222    10 32000]]


In [32]:
#print(new_arr.reshape(2,2,5))

In [24]:
arr3 = arr1 * arr2

In [25]:
new_arr = np.column_stack((arr1, arr2, arr3))

In [33]:
new_arr

array([[    1,  7000],
       [    2,  9777],
       [    3, 12555],
       [    4, 15333],
       [    5, 18111],
       [    6, 20888],
       [    7, 23666],
       [    8, 26444],
       [    9, 29222],
       [   10, 32000]])